In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("dataset.csv")
print(df.shape)

(2479, 47)

In [2]:
print(df.head())

   Time  Region Code Region  Total population (Both sexes)【person】  \
0  1920            0  Japan                               55963053
1  1925            0  Japan                               59736822
2  1930            0  Japan                               64450005
3  1935            0  Japan                               69254148
4  1940            0  Japan                               73075071

   Percentage distribution of total population (0-14)【%】  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Percentage distribution of total population (15-64)【%】  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Percentage distribution of total population (65 and over)【%】  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Total fertility rate  Live births【person】  Deaths【person】  ...  \
0                   NaN                  NaN             NaN  ...
1                   NaN                  NaN             NaN  ...
2                   NaN                  NaN             NaN  ...
3                   NaN                  NaN             NaN  ...
4                   NaN                  NaN             NaN  ...

   Prefectural income per person (2011 base)[thousand yen]  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Prefectural income per person (2015 base)[thousand yen]  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  Monthly household income (2+ person workers' households)[yen] Area (km²)  \
0                                                NaN             377975.64
1                                                NaN             377975.64
2                                                NaN             377975.64
3                                                NaN             377975.64
4                                                NaN             377975.64

  Total in-migrants (overall)【person】 Total out-migrants (overall)【person】  \
0                                 NaN                                  NaN
1                                 NaN                                  NaN
2                                 NaN                                  NaN
3                                 NaN                                  NaN
4                                 NaN                                  NaN

  DID Population【person】 Unemployment rate (Both sexes)[%]  \
0                    NaN                               NaN
1                    NaN                               NaN
2                    NaN                               NaN
3                    NaN                               NaN
4                    NaN                               NaN

   Life expectancy (Male)[years] Life expectancy (Female)[years]
0                            NaN                             NaN
1                            NaN                             NaN
2                            NaN                             NaN
3                            NaN                             NaN
4                            NaN                             NaN

[5 rows x 47 columns]

In [3]:
df.tail()

,Time,Region Code,Region,Total population (Both sexes)【person】,Percentage distribution of total population (0-14)【%】,Percentage distribution of total population (15-64)【%】,Percentage distribution of total population (65 and over)【%】,Total fertility rate,Live births【person】,Deaths【person】,...,Prefectural income per person (2011 base)[thousand yen],Prefectural income per person (2015 base)[thousand yen],Monthly household income (2+ person workers' households)[yen],Area (km²),Total in-migrants (overall)【person】,Total out-migrants (overall)【person】,DID Population【person】,Unemployment rate (Both sexes)[%],Life expectancy (Male)[years],Life expectancy (Female)[years]
2474,2025,43000,Kumamoto-ken,1678090,NaN,NaN,NaN,1.40,10193.0,24203.0,...,NaN,NaN,635814.0,7409.19,28923.0,31256.0,NaN,NaN,NaN,NaN
2475,2025,44000,Oita-ken,1076875,NaN,NaN,NaN,1.33,5666.0,16333.0,...,NaN,NaN,641665.0,6340.70,19302.0,22274.0,NaN,NaN,NaN,NaN
2476,2025,45000,Miyazaki-ken,1018904,NaN,NaN,NaN,1.46,5923.0,16107.0,...,NaN,NaN,578217.0,7734.16,17063.0,20087.0,NaN,NaN,NaN,NaN
2477,2025,46000,Kagoshima-ken,1512969,NaN,NaN,NaN,1.38,8661.0,23656.0,...,NaN,NaN,587787.0,9186.20,24814.0,29817.0,NaN,NaN,NaN,NaN
2478,2025,47000,Okinawa-ken,1468220,NaN,NaN,NaN,1.52,11511.0,15000.0,...,NaN,NaN,461206.0,2282.11,28499.0,29058.0,NaN,NaN,NaN,NaN

In [4]:
for i, col in enumerate(df.columns,start=1):
    print(i,col)

1 Time
2 Region Code
3 Region
4 Total population (Both sexes)【person】
5 Percentage distribution of total population (0-14)【%】
6 Percentage distribution of total population (15-64)【%】
7 Percentage distribution of total population (65 and over)【%】
8 Total fertility rate
9 Live births【person】
10 Deaths【person】
11 Number of in-migrants (Japanese)【person】
12 Number of out-migrants (Japanese)【person】
13 Annotation
14 Annotation.1
15 Annotation.2
16 Annotation.3
17 Annotation.4
18 Annotation.5
19 Annotation.6
20 Annotation_birth_outmigration
21 Annotation.1_birth_outmigration
22 Population (15-49, female)【person】
23 Marriages【pairs】
24 Annotation_marriages
25 Crude marriage rates (per 1,000 population)
26 Annotation_marriage_rate
27 Mean age of first marriage (Groom)【age】
28 Annotation_first_marriage_age_groom
29 Mean age of first marriage (Bride)【age】
30 Annotation_first_marriage_age_bride
31 Divorces 【pairs】
32 Annotation_divorces
33 Crude divorce rates (per 1,000 population)
34 Annotation_divorce_rate
35 Annual increase rate of prefectural income (2005 base)[%]
36 Annual increase rate of gross prefectural income (nominal) (2015 base)[%]
37 Prefectural income per person (2005 base)[thousand yen]
38 Prefectural income per person (2011 base)[thousand yen]
39 Prefectural income per person (2015 base)[thousand yen]
40 Monthly household income (2+ person workers' households)[yen]
41 Area (km²)
42 Total in-migrants (overall)【person】
43 Total out-migrants (overall)【person】
44 DID Population【person】
45 Unemployment rate (Both sexes)[%]
46 Life expectancy (Male)[years]
47 Life expectancy (Female)[years]

In [5]:
duplicates=df.duplicated(subset=["Time","Region Code"],keep=False)
print("Duplicate observations: ",duplicates.sum())
print("Completely duplicated rows :",df.duplicated().sum())

Duplicate observations:  0
Completely duplicated rows : 0

In [6]:
df.loc[duplicates,["Time","Region Code","Region"]].sort_values(by=["Time","Region Code"])

Empty DataFrame
Columns: [Time, Region Code, Region]
Index: []

In [7]:
print("No of regions:", df["Region Code"].nunique())

No of regions: 48

In [8]:
regions=(df[["Region Code","Region"]].drop_duplicates().sort_values("Region Code"))
print(regions.to_string(index=False))

 Region Code        Region
           0         Japan
        1000      Hokkaido
        2000    Aomori-ken
        3000     Iwate-ken
        4000    Miyagi-ken
        5000     Akita-ken
        6000  Yamagata-ken
        7000 Fukushima-ken
        8000   Ibaraki-ken
        9000   Tochigi-ken
       10000     Gumma-ken
       11000   Saitama-ken
       12000     Chiba-ken
       13000      Tokyo-to
       14000  Kanagawa-ken
       15000   Niigata-ken
       16000    Toyama-ken
       17000  Ishikawa-ken
       18000     Fukui-ken
       19000 Yamanashi-ken
       20000    Nagano-ken
       21000      Gifu-ken
       22000  Shizuoka-ken
       23000     Aichi-ken
       24000       Mie-ken
       25000     Shiga-ken
       26000      Kyoto-fu
       27000      Osaka-fu
       28000     Hyogo-ken
       29000      Nara-ken
       30000  Wakayama-ken
       31000   Tottori-ken
       32000   Shimane-ken
       33000   Okayama-ken
       34000 Hiroshima-ken
       35000 Yamaguchi-ken
       36000 Tokushima-ken
       37000    Kagawa-ken
       38000     Ehime-ken
       39000     Kochi-ken
       40000   Fukuoka-ken
       41000      Saga-ken
       42000  Nagasaki-ken
       43000  Kumamoto-ken
       44000      Oita-ken
       45000  Miyazaki-ken
       46000 Kagoshima-ken
       47000   Okinawa-ken

In [9]:
check=(df.groupby("Region Code")["Region"].nunique())
print(check[check>1])

Series([], Name: Region, dtype: int64)

In [10]:
print("First year:",df["Time"].min())
print("Last year:",df["Time"].max())

First year: 1920
Last year: 2025

In [11]:
print(sorted(df["Time"].unique()))
year_counts=df["Time"].value_counts().sort_index()
print(year_counts)

[np.int64(1920), np.int64(1925), np.int64(1930), np.int64(1935), np.int64(1940), np.int64(1945), np.int64(1950), np.int64(1951), np.int64(1952), np.int64(1953), np.int64(1954), np.int64(1955), np.int64(1956), np.int64(1957), np.int64(1958), np.int64(1959), np.int64(1960), np.int64(1961), np.int64(1962), np.int64(1963), np.int64(1964), np.int64(1965), np.int64(1966), np.int64(1967), np.int64(1968), np.int64(1969), np.int64(1970), np.int64(1971), np.int64(1972), np.int64(1973), np.int64(1974), np.int64(1975), np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]
Time
1920     1
1925     1
1930     1
1935     1
1940     1
        ..
2021    48
2022    48
2023    48
2024    48
2025    48
Name: count, Length: 82, dtype: int64

In [12]:
expected=df["Region"].nunique()*df["Time"].nunique()
print("Expected observations:",expected)
print("Actual observations:",len(df))

Expected observations: 3936
Actual observations: 2479

In [13]:
print(df.dtypes.to_string())

Time                                                                           int64
Region Code                                                                    int64
Region                                                                           str
Total population (Both sexes)【person】                                          int64
Percentage distribution of total population (0-14)【%】                        float64
Percentage distribution of total population (15-64)【%】                       float64
Percentage distribution of total population (65 and over)【%】                 float64
Total fertility rate                                                         float64
Live births【person】                                                          float64
Deaths【person】                                                               float64
Number of in-migrants (Japanese)【person】                                     float64
Number of out-migrants (Japanese)【person】                                    float64
Annotation                                                                       str
Annotation.1                                                                     str
Annotation.2                                                                     str
Annotation.3                                                                     str
Annotation.4                                                                     str
Annotation.5                                                                     str
Annotation.6                                                                 float64
Annotation_birth_outmigration                                                    str
Annotation.1_birth_outmigration                                              float64
Population (15-49, female)【person】                                           float64
Marriages【pairs】                                                             float64
Annotation_marriages                                                         float64
Crude marriage rates (per 1,000 population)                                  float64
Annotation_marriage_rate                                                         str
Mean age of first marriage (Groom)【age】                                      float64
Annotation_first_marriage_age_groom                                          float64
Mean age of first marriage (Bride)【age】                                      float64
Annotation_first_marriage_age_bride                                          float64
Divorces 【pairs】                                                             float64
Annotation_divorces                                                          float64
Crude divorce rates (per 1,000 population)                                   float64
Annotation_divorce_rate                                                          str
Annual increase rate of prefectural income (2005 base)[%]                    float64
Annual increase rate of gross prefectural income (nominal) (2015 base)[%]    float64
Prefectural income per person (2005 base)[thousand yen]                      float64
Prefectural income per person (2011 base)[thousand yen]                      float64
Prefectural income per person (2015 base)[thousand yen]                      float64
Monthly household income (2+ person workers' households)[yen]                float64
Area (km²)                                                                   float64
Total in-migrants (overall)【person】                                          float64
Total out-migrants (overall)【person】                                         float64
DID Population【person】                                                       float64
Unemployment rate (Both sexes)[%]                                            float64
Life expectancy (Male)[years]                                                float64
Life expectancy (Female)[years]                                              float64

In [14]:
print(df.select_dtypes(include="object").columns.to_list())

['Region', 'Annotation', 'Annotation.1', 'Annotation.2', 'Annotation.3', 'Annotation.4', 'Annotation.5', 'Annotation_birth_outmigration', 'Annotation_marriage_rate', 'Annotation_divorce_rate']

C:\Users\Hp\AppData\Local\Temp\ipykernel_11180\3293101278.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns.to_list())

In [15]:
missing=df.isna().sum()
print(missing[missing>0].sort_values(ascending=False))

Annotation.6                                                                 2479
Annotation.1_birth_outmigration                                              2479
Annotation_marriages                                                         2479
Annotation_first_marriage_age_groom                                          2479
Annotation_divorces                                                          2479
Annotation_first_marriage_age_bride                                          2479
Annotation_marriage_rate                                                     2478
Annotation_divorce_rate                                                      2478
Annotation.4                                                                 2431
Annotation_birth_outmigration                                                2431
Annotation.5                                                                 2431
Annotation                                                                   2393
Annotation.1                                                                 2280
Annotation.3                                                                 2280
Annotation.2                                                                 2280
Annual increase rate of gross prefectural income (nominal) (2015 base)[%]    1999
Life expectancy (Female)[years]                                              1999
DID Population【person】                                                       1999
Life expectancy (Male)[years]                                                1999
Unemployment rate (Both sexes)[%]                                            1999
Prefectural income per person (2015 base)[thousand yen]                      1999
Crude divorce rates (per 1,000 population)                                   1961
Crude marriage rates (per 1,000 population)                                  1961
Total in-migrants (overall)【person】                                          1903
Total out-migrants (overall)【person】                                         1903
Prefectural income per person (2011 base)[thousand yen]                      1855
Annual increase rate of prefectural income (2005 base)[%]                    1855
Prefectural income per person (2005 base)[thousand yen]                      1807
Percentage distribution of total population (0-14)【%】                        1488
Percentage distribution of total population (15-64)【%】                       1488
Percentage distribution of total population (65 and over)【%】                 1488
Live births【person】                                                           974
Total fertility rate                                                          504
Marriages【pairs】                                                              127
Divorces 【pairs】                                                              127
Mean age of first marriage (Bride)【age】                                       127
Mean age of first marriage (Groom)【age】                                       127
Population (15-49, female)【person】                                             68
Deaths【person】                                                                 34
Number of out-migrants (Japanese)【person】                                      31
Number of in-migrants (Japanese)【person】                                       31
Monthly household income (2+ person workers' households)[yen]                  31
dtype: int64

In [16]:
missing_pct=(df.isna().mean()*100).sort_values(ascending=False)
print(missing_pct[missing_pct>0])

Annotation_first_marriage_age_groom                                          100.000000
Annotation_divorces                                                          100.000000
Annotation_first_marriage_age_bride                                          100.000000
Annotation_marriages                                                         100.000000
Annotation.6                                                                 100.000000
Annotation.1_birth_outmigration                                              100.000000
Annotation_divorce_rate                                                       99.959661
Annotation_marriage_rate                                                      99.959661
Annotation.5                                                                  98.063735
Annotation.4                                                                  98.063735
Annotation_birth_outmigration                                                 98.063735
Annotation                                                                    96.530859
Annotation.3                                                                  91.972570
Annotation.1                                                                  91.972570
Annotation.2                                                                  91.972570
Life expectancy (Male)[years]                                                 80.637354
Life expectancy (Female)[years]                                               80.637354
Unemployment rate (Both sexes)[%]                                             80.637354
DID Population【person】                                                        80.637354
Annual increase rate of gross prefectural income (nominal) (2015 base)[%]     80.637354
Prefectural income per person (2015 base)[thousand yen]                       80.637354
Crude divorce rates (per 1,000 population)                                    79.104478
Crude marriage rates (per 1,000 population)                                   79.104478
Total out-migrants (overall)【person】                                          76.764825
Total in-migrants (overall)【person】                                           76.764825
Prefectural income per person (2011 base)[thousand yen]                       74.828560
Annual increase rate of prefectural income (2005 base)[%]                     74.828560
Prefectural income per person (2005 base)[thousand yen]                       72.892295
Percentage distribution of total population (0-14)【%】                         60.024203
Percentage distribution of total population (65 and over)【%】                  60.024203
Percentage distribution of total population (15-64)【%】                        60.024203
Live births【person】                                                           39.290036
Total fertility rate                                                          20.330779
Mean age of first marriage (Groom)【age】                                        5.123033
Marriages【pairs】                                                               5.123033
Divorces 【pairs】                                                               5.123033
Mean age of first marriage (Bride)【age】                                        5.123033
Population (15-49, female)【person】                                             2.743042
Deaths【person】                                                                 1.371521
Number of out-migrants (Japanese)【person】                                      1.250504
Number of in-migrants (Japanese)【person】                                       1.250504
Monthly household income (2+ person workers' households)[yen]                  1.250504
dtype: float64

In [17]:
pop = "Total population (Both sexes)【person】"
print(df[pop].describe())

count    2.479000e+03
mean     6.231235e+06
std      1.988101e+07
min      5.237320e+05
25%      1.149000e+06
50%      1.770254e+06
75%      2.882000e+06
max      1.280840e+08
Name: Total population (Both sexes)【person】, dtype: float64

In [18]:
print("Negative: ",(df[pop]<0).sum())
print("Zero: ",(df[pop]==0).sum())

Negative:  0
Zero:  0

In [19]:
age_cols = [
    "Percentage distribution of total population (0-14)【%】",
    "Percentage distribution of total population (15-64)【%】",
    "Percentage distribution of total population (65 and over)【%】"
]
df["age_share_sum"]=df[age_cols].sum(axis=1,min_count=3)
print(df[age_cols].isna().all(axis=1).sum())

print(df["age_share_sum"].describe())
bad_age=df[df["age_share_sum"].notna() & ((df["age_share_sum"]<98.6)|(df["age_share_sum"]>101))]
print(df.loc[df["age_share_sum"].notna(),["Time","Region","age_share_sum"]].sort_values(by='age_share_sum').head(5))
print(df.loc[df["age_share_sum"].notna(),"age_share_sum"].sort_values().tail(5))
print("Age-share anomalies",len(bad_age))

for col in age_cols:
    print(col,
          "negative: ",(df[col]<=0).sum(),
          "above 100: ",(df[col]>=100).sum()
          )

1488
count    991.000000
mean      99.990706
std        0.083578
min       98.700000
25%      100.000000
50%      100.000000
75%      100.000000
max      100.100000
Name: age_share_sum, dtype: float64
      Time         Region  age_share_sum
1484  2005       Tokyo-to           98.7
1497  2005       Kyoto-fu           99.3
1498  2005       Osaka-fu           99.3
1485  2005   Kanagawa-ken           99.5
1505  2005  Hiroshima-ken           99.5
2053    100.1
2004    100.1
2198    100.1
2199    100.1
2276    100.1
Name: age_share_sum, dtype: float64
Age-share anomalies 0
Percentage distribution of total population (0-14)【%】 negative:  0 above 100:  0
Percentage distribution of total population (15-64)【%】 negative:  0 above 100:  0
Percentage distribution of total population (65 and over)【%】 negative:  0 above 100:  0

In [20]:
df=df.sort_values(["Region Code","Time"])
df["Population change"]=(df.groupby("Region Code")[pop].diff())
df["Net Migration"] = (
    df["Total in-migrants (overall)【person】"]
    - df["Total out-migrants (overall)【person】"]
)
print(df["Net Migration"].describe())
df["Expected Population Change"]=(
   df["Live births【person】"] - df["Deaths【person】"]  + df["Net Migration"]
)
accounting=df.dropna(
    subset=[
        "Population change",
        "Live births【person】",
        "Deaths【person】",
        "Net Migration"
    ],how="any").copy()
accounting["Accounting Difference"]=(accounting["Population change"]-accounting["Expected Population Change"])
print("Population change NA:", df["Population change"].isna().sum())
print("Accounting rows:", len(accounting))

count      576.000000
mean         0.000000
std      11736.351336
min     -11409.000000
25%      -4321.000000
50%      -2480.500000
75%      -1013.250000
max      84231.000000
Name: Net Migration, dtype: float64
Population change NA: 48
Accounting rows: 576

In [21]:
fertility="Total fertility rate"
print(df[fertility].describe())
print("Negative: ",(df[fertility]<0).sum())
print("Zero: ",(df[fertility]==0).sum())
print("Missing: ",df[fertility].isna().sum())
print(df.nsmallest(10,fertility)[["Time","Region Code","Region",fertility]])
print(df.nlargest(10,fertility)[["Time","Region Code","Region",fertility]])

count    1975.000000
mean        1.480278
std         0.187142
min         0.960000
25%         1.360000
50%         1.470000
75%         1.600000
max         2.310000
Name: Total fertility rate, dtype: float64
Negative:  0
Zero:  0
Missing:  504
      Time  Region Code      Region  Total fertility rate
2396  2024        13000    Tokyo-to                  0.96
2444  2025        13000    Tokyo-to                  0.96
2348  2023        13000    Tokyo-to                  0.99
2432  2025         1000    Hokkaido                  1.00
2387  2024         4000  Miyagi-ken                  1.00
2435  2025         4000  Miyagi-ken                  1.00
1292  2001        13000    Tokyo-to                  1.00
1388  2003        13000    Tokyo-to                  1.00
1484  2005        13000    Tokyo-to                  1.00
2384  2024         1000    Hokkaido                  1.01
     Time  Region Code         Region  Total fertility rate
558  1985        47000    Okinawa-ken                  2.31
606  1986        47000    Okinawa-ken                  2.27
654  1987        47000    Okinawa-ken                  2.15
702  1988        47000    Okinawa-ken                  2.10
750  1989        47000    Okinawa-ken                  2.02
846  1991        47000    Okinawa-ken                  2.02
543  1985        32000    Shimane-ken                  2.01
591  1986        32000    Shimane-ken                  2.00
639  1987        32000    Shimane-ken                  1.99
518  1985         7000  Fukushima-ken                  1.98

In [22]:
for col in ["Live births【person】",
    "Deaths【person】"]:
    print("\n",col)
    print(df[col].describe())
    print("Negative: ",(df[col]<0).sum())
    print("Zero: ",(df[col]==0).sum())
    print("Missing: ",df[col].isna().sum())

 Live births【person】
count    1.505000e+03
mean     5.770115e+04
std      2.044792e+05
min      2.973000e+03
25%      8.626000e+03
50%      1.366300e+04
75%      2.482900e+04
max      1.708643e+06
Name: Live births【person】, dtype: float64
Negative:  0
Zero:  0
Missing:  974

 Deaths【person】
count    2.445000e+03
mean     4.202468e+04
std      1.487566e+05
min      4.674000e+03
25%      1.012600e+04
50%      1.532600e+04
75%      2.557400e+04
max      1.605378e+06
Name: Deaths【person】, dtype: float64
Negative:  0
Zero:  0
Missing:  34

In [23]:
migration_cols = [
    "Total in-migrants (overall)【person】",
    "Total out-migrants (overall)【person】"
]
for col in migration_cols:
    print("\n",col)
    print(df[col].describe())
    print("Negative: ",(df[col]<0).sum())
    print("Zero: ",(df[col]==0).sum())
    print("Missing: ",df[col].isna().sum())

 Total in-migrants (overall)【person】
count    5.760000e+02
mean     1.043569e+05
std      3.586445e+05
min      7.781000e+03
25%      1.671200e+04
50%      2.694150e+04
75%      5.257200e+04
max      2.568086e+06
Name: Total in-migrants (overall)【person】, dtype: float64
Negative:  0
Zero:  0
Missing:  1903

 Total out-migrants (overall)【person】
count    5.760000e+02
mean     1.043569e+05
std      3.566333e+05
min      9.582000e+03
25%      1.951750e+04
50%      2.980150e+04
75%      5.775475e+04
max      2.568086e+06
Name: Total out-migrants (overall)【person】, dtype: float64
Negative:  0
Zero:  0
Missing:  1903

In [24]:
for col in migration_cols:
    print(col,sorted(df.loc[df[col].notna(),"Time"].unique()))

Total in-migrants (overall)【person】 [np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]
Total out-migrants (overall)【person】 [np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

In [25]:
area = "Area (km²)"
print(df[area].describe())
print("0 or less than 0:",(df[area]==0).sum())

count      2479.000000
mean      20278.644869
std       67143.432656
min        1876.860000
25%        4186.200000
50%        6113.000000
75%        8478.160000
max      377975.640000
Name: Area (km²), dtype: float64
0 or less than 0: 0

In [26]:
did = "DID Population【person】"
print(df[did].describe())
print(df.loc[df[did].notna(),"Time"].unique())
print("Negative or 0: ",(df[did]<=0).sum())

count    4.800000e+02
mean     3.312189e+06
std      1.143354e+07
min      1.517070e+05
25%      4.285745e+05
50%      7.092770e+05
75%      1.829925e+06
max      8.828593e+07
Name: DID Population【person】, dtype: float64
[1975 1980 1985 1990 1995 2000 2005 2010 2015 2020]
Negative or 0:  0

In [27]:
unemp = "Unemployment rate (Both sexes)[%]"
print(df[unemp].describe())
print(sorted(df.loc[df[unemp].notna(),"Time"].unique()))

count    480.000000
mean       4.006458
std        1.669629
min        1.200000
25%        2.800000
50%        3.850000
75%        4.900000
max       11.900000
Name: Unemployment rate (Both sexes)[%], dtype: float64
[np.int64(1975), np.int64(1980), np.int64(1985), np.int64(1990), np.int64(1995), np.int64(2000), np.int64(2005), np.int64(2010), np.int64(2015), np.int64(2020)]

In [28]:
print(df.loc[df[unemp].notna() & ((df[unemp]<0) | (df[unemp]>100)),["Time","Region",unemp]])

Empty DataFrame
Columns: [Time, Region, Unemployment rate (Both sexes)[%]]
Index: []

In [29]:
life_cols = [
    "Life expectancy (Male)[years]",
    "Life expectancy (Female)[years]"
]
for col in life_cols:
    print("\n",col)
    print(df[col].describe())

 Life expectancy (Male)[years]
count    480.000000
mean      77.016292
std        3.100444
min       69.690000
25%       74.817500
50%       77.140000
75%       79.542500
max       82.730000
Name: Life expectancy (Male)[years], dtype: float64

 Life expectancy (Female)[years]
count    480.000000
mean      83.371458
std        3.472866
min       75.860000
25%       80.832500
50%       84.125000
75%       86.382500
max       88.290000
Name: Life expectancy (Female)[years], dtype: float64

In [30]:
for col in life_cols:
    print("\n",col)
    print(sorted(df.loc[df[col].notna(),"Time"].unique()))

 Life expectancy (Male)[years]
[np.int64(1975), np.int64(1980), np.int64(1985), np.int64(1990), np.int64(1995), np.int64(2000), np.int64(2005), np.int64(2010), np.int64(2015), np.int64(2020)]

 Life expectancy (Female)[years]
[np.int64(1975), np.int64(1980), np.int64(1985), np.int64(1990), np.int64(1995), np.int64(2000), np.int64(2005), np.int64(2010), np.int64(2015), np.int64(2020)]

In [31]:
for col in life_cols:
    print(col," Values- 0 or less ",(df[col]<=0).sum())
    print(col,"Values that are null ",(df[col].isna()).sum())

Life expectancy (Male)[years]  Values- 0 or less  0
Life expectancy (Male)[years] Values that are null  1999
Life expectancy (Female)[years]  Values- 0 or less  0
Life expectancy (Female)[years] Values that are null  1999

In [32]:
income_cols=[col for col in df.columns if "income" in col.lower()]
print(income_cols)

['Annual increase rate of prefectural income (2005 base)[%]', 'Annual increase rate of gross prefectural income (nominal) (2015 base)[%]', 'Prefectural income per person (2005 base)[thousand yen]', 'Prefectural income per person (2011 base)[thousand yen]', 'Prefectural income per person (2015 base)[thousand yen]', "Monthly household income (2+ person workers' households)[yen]"]

In [33]:
df[income_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Annual increase rate of prefectural income (2005 base)[%],624.0,-0.156090,3.208935,-14.3,-1.600,0.1,1.7,9.7
Annual increase rate of gross prefectural income (nominal) (2015 base)[%],480.0,1.080833,2.859159,-6.6,-0.725,1.0,3.2,8.8
Prefectural income per person (2005 base)[thousand yen],672.0,2777.471726,436.670729,1985.0,2472.000,2760.0,2967.0,5266.0
Prefectural income per person (2011 base)[thousand yen],624.0,2780.831731,512.656095,1933.0,2464.750,2733.5,2975.0,5970.0
Prefectural income per person (2015 base)[thousand yen],480.0,2904.325000,512.599196,2020.0,2635.250,2861.0,3056.0,5919.0
Monthly household income (2+ person workers' households)[yen],2448.0,506516.674428,109635.738903,210085.0,440755.000,524323.5,581602.0,814226.0

In [34]:
annotation_cols=[col for col in df.columns if "annotation" in col.lower()]
print(annotation_cols)
for col in annotation_cols:
    print(col,"\nNot Null Values",df[col].notna().sum())

['Annotation', 'Annotation.1', 'Annotation.2', 'Annotation.3', 'Annotation.4', 'Annotation.5', 'Annotation.6', 'Annotation_birth_outmigration', 'Annotation.1_birth_outmigration', 'Annotation_marriages', 'Annotation_marriage_rate', 'Annotation_first_marriage_age_groom', 'Annotation_first_marriage_age_bride', 'Annotation_divorces', 'Annotation_divorce_rate']
Annotation
Not Null Values 86
Annotation.1
Not Null Values 199
Annotation.2
Not Null Values 199
Annotation.3
Not Null Values 199
Annotation.4
Not Null Values 48
Annotation.5
Not Null Values 48
Annotation.6
Not Null Values 0
Annotation_birth_outmigration
Not Null Values 48
Annotation.1_birth_outmigration
Not Null Values 0
Annotation_marriages
Not Null Values 0
Annotation_marriage_rate
Not Null Values 1
Annotation_first_marriage_age_groom
Not Null Values 0
Annotation_first_marriage_age_bride
Not Null Values 0
Annotation_divorces
Not Null Values 0
Annotation_divorce_rate
Not Null Values 1

In [35]:
print(df["Region Code"].head(20))
print(df["Region Code"].dtype)
codes=df["Region Code"].astype(str)
print(codes.str.len().value_counts())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: Region Code, dtype: int64
int64
Region Code
5    1938
4     459
1      82
Name: count, dtype: int64

In [36]:
five_year_cols = [
    "DID Population【person】",
    "Unemployment rate (Both sexes)[%]",
    "Life expectancy (Male)[years]",
    "Life expectancy (Female)[years]"
]
for col in five_year_cols:
    print("\n"+col)
    print(sorted(df.loc[df[col].notna(),"Time"].unique()))

DID Population【person】
[np.int64(1975), np.int64(1980), np.int64(1985), np.int64(1990), np.int64(1995), np.int64(2000), np.int64(2005), np.int64(2010), np.int64(2015), np.int64(2020)]

Unemployment rate (Both sexes)[%]
[np.int64(1975), np.int64(1980), np.int64(1985), np.int64(1990), np.int64(1995), np.int64(2000), np.int64(2005), np.int64(2010), np.int64(2015), np.int64(2020)]

Life expectancy (Male)[years]
[np.int64(1975), np.int64(1980), np.int64(1985), np.int64(1990), np.int64(1995), np.int64(2000), np.int64(2005), np.int64(2010), np.int64(2015), np.int64(2020)]

Life expectancy (Female)[years]
[np.int64(1975), np.int64(1980), np.int64(1985), np.int64(1990), np.int64(1995), np.int64(2000), np.int64(2005), np.int64(2010), np.int64(2015), np.int64(2020)]

In [37]:
df.drop(columns=["age_share_sum"],inplace=True)